### ISSUE TITLE
Errror when using train_asmlp_b.sh

### ISSUE THREAD

**Issue by HantingChen** [svip-lab/AS-MLP#1]
When using train_asmlp_b.sh, the above error occurs:

  File "/home/ma-user/work/AS-MLP-main/models/as_mlp.py", line 165, in forward
    x = shortcut + self.drop_path(x)
  File "/home/ma-user/anaconda3/envs/Pytorch-1.4.0/lib/python3.6/site-packages/apex/amp/wrap.py", line 58, in wrapper
    return orig_fn(*new_args, **kwargs)
RuntimeError: The size of tensor a (56) must match the size of tensor b (60) at non-singleton dimension 3

**Comment by wp2333** [comment]
I get this error too. did you solve it?

**Comment by HantingChen** [comment]
> I get this error too. did you solve it?

I am trying to fix it. It seems that the AxialShift block changes the size (https://github.com/svip-lab/AS-MLP/blob/f9b4000d18a1c3dc5a8dfd30e881c4f44712cb02/models/as_mlp.py#L162).

They pad the input (https://github.com/svip-lab/AS-MLP/blob/f9b4000d18a1c3dc5a8dfd30e881c4f44712cb02/models/as_mlp.py#L69) but without shrinking it.  

![image](https://user-images.githubusercontent.com/40243544/126467444-ca2a09f1-9618-418a-8720-3fa2f33c934c.png)

**Comment by niujinshuchong** [comment]
@HantingChen @wp2333 
Thanks for pointing this. Yes, we should comment this line https://github.com/svip-lab/AS-MLP/blob/main/models/as_mlp.py#L70.

I updated the code and it should solve this error.
