### ISSUE TITLE
Reproduce the accuracy in paper

### ISSUE THREAD

**Issue by Gaffey** [svip-lab/AS-MLP#12]
Hello, thanks for sharing your work. We have tride the code on AS-MLP-T, and only get 81.13/81.06 in two seperate experiments. Are there any settings needed to be modified?

**Comment by Gaffey** [comment]
@dongzelian Thank you for your kind reply. Besides, I find a small difference between the code and the paper. The initial learning rate is set as 0.0005 in the code (BASE_LR in config.py) and 0.001 in the paper, which is the final used one?

**Comment by dongzelian** [comment]
@Gaffey Hi, the initial learning rate is 0.001, which is consistent with the value in the paper. Please note the batch size is 1024 (128/per GPU * 8GPUs) and refer to this line https://github.com/svip-lab/AS-MLP/blob/5f360348583b3cac8663a392c9588b6f7e2f46b8/main.py#L319

**Comment by Gaffey** [comment]
@dongzelian got it, thanks again.
