### ISSUE TITLE
Semantic Segmentation?

### ISSUE THREAD

**Issue by Dootmaan** [svip-lab/AS-MLP#15]
Thank you for your work! 
However, I did not find your code for semantic segmentation. I am currently working on pure-MLP segmentation and it would be a huge help if you could provide the ASMLP code for semantic segmentation.

**Comment by dongzelian** [comment]
@Dootmaan Thanks for your attention. You can refer to https://github.com/svip-lab/AS-MLP-Semantic-Segmentation
