### ISSUE TITLE
Will the throughput change a lot whether using shift_cuda or just torch functions?

### ISSUE THREAD

**Issue by laisimiao** [svip-lab/AS-MLP#16]
Do you have data about this?

**Comment by niujinshuchong** [comment]
Hi, our cuda kernel is 10 times faster compared to torch functions. However, since the shift operation is only a small part of the network forward pass, the overall improvements is not big. I think the throughput can be increase by 10% (don't remember the exact number).

**Comment by laisimiao** [comment]
👌thanks
