### ISSUE TITLE
Training strategy on Imagenet

### ISSUE THREAD

**Issue by Ga-Lee** [svip-lab/AS-MLP#18]
Hello! Thank you  for your wonderful job!
it is said that as-mlp uses the same training strategy in Swin Transformer, I want to know to what extend the work use the same strategy ? For example, does as-mlp use Mixup、Cutmix?  
I saw there exists codes for mixup in function build_loader which requires config.AUG.MIXUP, but I didn't find config.AUG in the config file for  models.
I want to know the detailed training setting for your models, may you do the favor for me?

**Comment by dongzelian** [comment]
@Ga-Lee Thanks so much!
(1) does as-mlp use Mixup、Cutmix? Yes.
(2) where is config.AUG? The config.AUG.MIXUP is here: https://github.com/svip-lab/AS-MLP/blob/da82a966e540b8b22a02bf8507d6174908d9f061/config.py#L119
(3) detailed training setting. You can refer to https://github.com/svip-lab/AS-MLP/blob/main/data/build.py,  https://github.com/svip-lab/AS-MLP/blob/main/config.py, and Sec. A.2 in Swin Transformer paper (https://arxiv.org/pdf/2103.14030.pdf).

**Comment by Ga-Lee** [comment]
@dongzelian 
Thank you for your kindness and reply!
no more questions, and  I will close the  issue.   : )
