### ISSUE TITLE
Question on the Shift CUDA implementation.

### ISSUE THREAD

**Issue by XiaoqiangZhou** [svip-lab/AS-MLP#19]
Thanks for sharing such a simple yet effective backbone work~

When I run the code, I find no noticeable runtime difference between using the shift_cuda.py and using Algorithm 1 in the paper with Pytorch itself. 

Do I miss something to activate the CUDA acceleration?

In fact, I copy part of the core codes in this repo and integrate the codes to the Swin Transformer, instead of running this repo directly.

Could you please help me with this problem? Thanks~

**Comment by niujinshuchong** [comment]
Hi, please refer to https://github.com/svip-lab/AS-MLP/issues/16.

**Comment by XiaoqiangZhou** [comment]
Thanks for your quick reply~
