### ISSUE TITLE
论文内容问题

### ISSUE THREAD

**Issue by qdd1234** [svip-lab/AS-MLP#2]
作者您好:
       您论文提及的轴转换对应到后面采样点，我想问一下本文中这个采样点和轴转换对应是什么，换句话说本文采样点这样分布怎么理解，谢谢
![image](https://user-images.githubusercontent.com/68497831/126494178-5992ea6e-c5db-42d4-8ebc-37217f9ca1f6.png)
![image](https://user-images.githubusercontent.com/68497831/126494359-5ef6ccf2-3ee0-440b-b1b9-43f68a8cfe6f.png)

**Comment by dongzelian** [comment]
@qdd1234 你好，这里的采样点意味着感受野。例如，最后一张图，当shift size为3，dilation为2时感受野的情况。上面的图仅仅显示horizontal shift，当horizontal shift和vertical shift同时使用时，就将产生下图的感受野。
